#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model Assignment2
 Dymola Version 2023 (64-bit), 2022-04-13 translated this at Sat Dec 16 01:44:22 2023

   */

#include <matrixop.h>
#include "matrixop.c"
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    7
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    99
#define NWP_   48
#define NP_    67
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -1162171381
#define NHash2_ -1325801259
#define NHash3_ 0
#define NI_    0
#define NRelF_ 14
#define NRel_  14
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    70
#define SizePre_ 4
#define SizeEq_ 8
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 4
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 12
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Assignment2";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[15]={5 , 2 , 1 , 4 , 1 , 2 , 1 , 3 , 2 , 5 , 6 , 1
   , 7 , 0 , 0};
static int QJacobianGrp0[8]={1, 1, 4, 0, 4, 0, 0, 0};
static int QJacobianGrp1[8]={2, 2, 2, 0, 0, 0, 2, 0};
static int QJacobianGrp2[8]={3, 3, 3, 0, 3, 0, 0, 0};
static int QJacobianGrp3[8]={6, 6, 5, 0, 5, 0, 6, 0};
static int QJacobianGrp4[7]={1, 7 , 3 , 1 , 2 , 7 , 0};
DYMOLA_STATIC struct QJacobianTag_ QJacobianGC2_[6]={
{0, QJacobianGrp0},{0, QJacobianGrp1},{0, QJacobianGrp2},{0, QJacobianGrp3},{1, 
  QJacobianGrp4},{0,0}};
DYMOLA_STATIC double QJacobianCD_[8]={0  , 44 , 50 , 54 , 77 , 64 , 72 , 70};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations
InitialSection
#if defined(DynSimStruct)
DYNX(W_,58) = 288.15;
DYNX(W_,62) = 0;
DYNX(W_,64) = 288.15;
DYNX(W_,65) = 288.15;
DYNX(W_,67) = 288.15;
DYNX(W_,48) = 0;
DYNX(W_,80) = 288.15;
DYNX(W_,81) = 288.15;
DYNX(W_,89) = 288.15;
DYNX(W_,92) = 0.8;
DYNX(W_,93) = 288.15;
DYNX(W_,97) = 0.0001;
DYNX(F_,0) = 0;
#endif

InitialSection
#if defined(DynSimStruct)
DYNX(W_,1) = true;
DYNX(W_,15) = true;
DYNX(W_,17) = true;
DYNX(W_,30) = true;
DYNX(W_,32) = true;
DYNX(W_,38) = true;
DYNX(W_,39) = true;
DYNX(W_,40) = true;
DYNX(W_,46) = true;
DYNX(W_,47) = true;
DYNX(W_,18) = 1;
DYNX(W_,0) = 0.5026548245743669;
DYNX(W_,12) = 0.1;
DYNX(W_,16) = 0.5026548245743669;
DYNX(W_,19) = 0;
DYNX(W_,31) = 0;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
AssertModelica(DYNX(DP_,27) > DYNX(DP_,26),"hysteresisT.uHigh > hysteresisT.uLow",
   "Hysteresis limits wrong (uHigh <= uLow)");
AssertModelica(DYNX(DP_,32) > DYNX(DP_,31),"hysteresisT3.uHigh > hysteresisT3.uLow",
   "Hysteresis limits wrong (uHigh <= uLow)");
AssertModelica(DYNX(DP_,60) > DYNX(DP_,59),"hysteresis.uHigh > hysteresis.uLow",
   "Hysteresis limits wrong (uHigh <= uLow)");
AssertModelica(DYNX(DP_,63) > DYNX(DP_,62),"hysteresis1.uHigh > hysteresis1.uLow",
   "Hysteresis limits wrong (uHigh <= uLow)");
BoundParameterSection
DYNX(W_,2) = DYNX(DP_,5);
DYNX(W_,3) = DYNX(DP_,6);
DYNX(W_,4) = DYNX(DP_,7);
DYNX(W_,5) = DYNX(DP_,8);
DYNX(W_,6) = DYNX(DP_,9);
DYNX(W_,7) = DYNX(DP_,5);
DYNX(W_,8) = DYNX(DP_,6);
DYNX(W_,9) = DYNX(DP_,7);
DYNX(W_,10) = DYNX(DP_,8);
DYNX(W_,11) = DYNX(DP_,9);
DYNX(DYNhelp,0) = divinvGuarded(DYNX(W_,12),"pipe.V_flowLaminar");
DYNX(W_,13) = DYNX(DYNhelp,0)*DYNX(DP_,12)*DYNX(DP_,13);
DYNX(W_,20) = DYNX(DP_,19);
DYNX(W_,21) = DYNX(DP_,20);
DYNX(W_,22) = DYNX(DP_,21);
DYNX(W_,23) = DYNX(DP_,22);
DYNX(W_,24) = DYNX(DP_,23);
DYNX(W_,25) = DYNX(DP_,19);
AssertModelica(fabs(DYNX(W_,25)-DYNX(W_,7)) <= 0.0,"abs(volumeFlow.flowPort_b.medium.rho-pipe.flowPort_b.medium.rho) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,26) = DYNX(DP_,20);
AssertModelica(fabs(DYNX(W_,26)-DYNX(W_,8)) <= 0.0,"abs(volumeFlow.flowPort_b.medium.cp-pipe.flowPort_b.medium.cp) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,27) = DYNX(DP_,21);
AssertModelica(fabs(DYNX(W_,27)-DYNX(W_,9)) <= 0.0,"abs(volumeFlow.flowPort_b.medium.cv-pipe.flowPort_b.medium.cv) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,28) = DYNX(DP_,22);
AssertModelica(fabs(DYNX(W_,28)-DYNX(W_,10)) <= 0.0,"abs(volumeFlow.flowPort_b.medium.lambda-pipe.flowPort_b.medium.lambda) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,29) = DYNX(DP_,23);
AssertModelica(fabs(DYNX(W_,29)-DYNX(W_,11)) <= 0.0,"abs(volumeFlow.flowPort_b.medium.nu-pipe.flowPort_b.medium.nu) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,33) = DYNX(DP_,37);
AssertModelica(fabs(DYNX(W_,20)-DYNX(W_,33)) <= 0.0,"abs(volumeFlow.flowPort_a.medium.rho-openTank1.flowPort.medium.rho) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,34) = DYNX(DP_,38);
AssertModelica(fabs(DYNX(W_,21)-DYNX(W_,34)) <= 0.0,"abs(volumeFlow.flowPort_a.medium.cp-openTank1.flowPort.medium.cp) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,35) = DYNX(DP_,39);
AssertModelica(fabs(DYNX(W_,22)-DYNX(W_,35)) <= 0.0,"abs(volumeFlow.flowPort_a.medium.cv-openTank1.flowPort.medium.cv) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,36) = DYNX(DP_,40);
AssertModelica(fabs(DYNX(W_,23)-DYNX(W_,36)) <= 0.0,"abs(volumeFlow.flowPort_a.medium.lambda-openTank1.flowPort.medium.lambda) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,37) = DYNX(DP_,41);
AssertModelica(fabs(DYNX(W_,24)-DYNX(W_,37)) <= 0.0,"abs(volumeFlow.flowPort_a.medium.nu-openTank1.flowPort.medium.nu) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,41) = DYNX(DP_,47);
AssertModelica(fabs(DYNX(W_,2)-DYNX(W_,41)) <= 0.0,"abs(pipe.flowPort_a.medium.rho-openTank3.flowPort.medium.rho) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,42) = DYNX(DP_,48);
AssertModelica(fabs(DYNX(W_,3)-DYNX(W_,42)) <= 0.0,"abs(pipe.flowPort_a.medium.cp-openTank3.flowPort.medium.cp) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,43) = DYNX(DP_,49);
AssertModelica(fabs(DYNX(W_,4)-DYNX(W_,43)) <= 0.0,"abs(pipe.flowPort_a.medium.cv-openTank3.flowPort.medium.cv) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,44) = DYNX(DP_,50);
AssertModelica(fabs(DYNX(W_,5)-DYNX(W_,44)) <= 0.0,"abs(pipe.flowPort_a.medium.lambda-openTank3.flowPort.medium.lambda) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,45) = DYNX(DP_,51);
AssertModelica(fabs(DYNX(W_,6)-DYNX(W_,45)) <= 0.0,"abs(pipe.flowPort_a.medium.nu-openTank3.flowPort.medium.nu) <= 0.0",
   "Parameters in connected connectors must be equal");
InitialSection
InitialStartSection
InitialStartSection2
DYNX(W_,68) = DYNX(DP_,6)*DYNX(DP_,10);
DYNX(W_,83) = DYNX(DP_,20)*DYNX(DP_,24);
DYNX(W_,90) = DYNX(DP_,42);
DYNX(W_,94) = DYNX(DP_,52);
DYNX(X_,1) = DYNX(DP_,10);
DYNX(X_,2) = DYNX(DP_,24);
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialBoundSection
DYNX(Aux_,0) = DYNX(W_,54);
DYNX(Aux_,1) = DYNX(W_,56);
DYNX(Aux_,2) = DYNX(W_,49);
DYNX(Aux_,3) = DYNX(W_,51);
InitialSection
InitialSection2
  AssertModelica(DYNX(DP_,13) > 0.1,"pipe.V_flowNominal > 0.1", "SimpleFriction: V_flowNominal has to be > V_flowLaminar!");
  AssertModelica(DYNX(DP_,14) >= DYNX(W_,13),"pipe.dpNominal >= pipe.dpNomMin", 
    "SimpleFriction: dpNominal has to be > dpLaminar/V_flowLaminar*V_flowNominal!");
  DYNX(W_,14) = divGuarded(DYNX(DP_,14)-DYNX(W_,13),"pipe.dpNominal-pipe.dpNomMin",
    sqr(DYNX(DP_,13)-0.1),"(pipe.V_flowNominal-0.1)^2");
DYNX(X_,3) = DYNX(DP_,37)*DYNX(DP_,43)*DYNX(W_,92);
DYNX(X_,2) = DYNX(DP_,24);
DYNX(X_,5) = DYNX(DP_,47)*DYNX(DP_,53)*DYNX(W_,97);
DYNX(W_,94) = DYNX(DP_,52);
DYNX(W_,95) = DYNX(W_,94)*DYNX(DP_,48);
DYNX(X_,6) = DYNX(X_,5)*DYNX(W_,95);
DYNX(X_,1) = DYNX(DP_,10);
DYNX(W_,90) = DYNX(DP_,42);
DYNX(W_,91) = DYNX(W_,90)*DYNX(DP_,38);
DYNX(X_,4) = DYNX(X_,3)*DYNX(W_,91);
InitialBoundSection
DYNX(Aux_,0) = DYNX(DP_,61);
DYNX(Aux_,1) = DYNX(DP_,64);
DYNX(Aux_,2) = DYNX(DP_,28);
DYNX(Aux_,3) = DYNX(DP_,33);
InitialSection
InitialSection2
DYNX(W_,54) = DYNX(Aux_,0);
DYNX(W_,56) = DYNX(Aux_,1);
DYNX(W_,49) = DYNX(Aux_,2);
DYNX(W_,51) = DYNX(Aux_,3);
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
 /* Linear system of equations to solve. */
DYNX(W_,92) = RememberSimple_(DYNX(W_,92), 0);
SolveScalarLinearParametric( -DYNX(DP_,37)*DYNX(DP_,43)," -openTank1.medium.rho*openTank1.ATank",
    -DYNX(X_,3)," -openTank1.m", DYNX(W_,92),"openTank1.level");
 /* End of Equation Block */ 

AssertModelica(GreaterEqual(DYNX(W_,92),"openTank1.level", 0,"0", 0),
  "openTank1.level >= 0", "Tank got empty!");
 /* Linear system of equations to solve. */
DYNX(W_,97) = RememberSimple_(DYNX(W_,97), 1);
SolveScalarLinearParametric( -DYNX(DP_,47)*DYNX(DP_,53)," -openTank3.medium.rho*openTank3.ATank",
    -DYNX(X_,5)," -openTank3.m", DYNX(W_,97),"openTank3.level");
 /* End of Equation Block */ 

AssertModelica(GreaterEqual(DYNX(W_,97),"openTank3.level", 0,"0", 1),
  "openTank3.level >= 0", "Tank got empty!");
DYNX(W_,98) = DYNX(W_,92)-DYNX(W_,97);
DYNX(W_,56) =  NOT PRE(DYNX(W_,56), 1) AND Greater(DYNX(W_,98),"hysteresis1.u", 
  DYNX(DP_,63),"hysteresis1.uHigh", 2) OR PRE(DYNX(W_,56), 1) AND GreaterEqual(
  DYNX(W_,98),"hysteresis1.u", DYNX(DP_,62),"hysteresis1.uLow", 3);
DYNX(W_,55) = IF DYNX(W_,56) THEN DYNX(DP_,65) ELSE DYNX(DP_,66);
DYNX(W_,87) = DYNX(X_,0)-273.15;
DYNX(W_,49) =  NOT PRE(DYNX(W_,49), 2) AND Greater(DYNX(W_,87),"hysteresisT.u", 
  DYNX(DP_,27),"hysteresisT.uHigh", 4) OR PRE(DYNX(W_,49), 2) AND GreaterEqual(
  DYNX(W_,87),"hysteresisT.u", DYNX(DP_,26),"hysteresisT.uLow", 5);
DYNX(W_,50) = IF DYNX(W_,49) THEN DYNX(DP_,29) ELSE DYNX(DP_,36);
DYNX(W_,48) = DYNX(W_,55)*DYNX(W_,50);
DYNX(F_,3) =  -DYNX(W_,48)*DYNX(DP_,19);
 /* Linear system of equations to solve. */
DYNX(W_,91) = RememberSimple_(DYNX(W_,91), 2);
SolveScalarLinear( -DYNX(X_,3)," -openTank1.m",  -DYNX(X_,4)," -openTank1.H", 
  DYNX(W_,91),"openTank1.h");
 /* End of Equation Block */ 

DYNX(W_,83) = DYNX(DP_,20)*DYNX(X_,2);
DYNX(DYNhelp,1) =  -DYNX(F_,3) >= 0;
DYNX(W_,86) = IF DYNX(DYNhelp,1) THEN  -DYNX(W_,91)*DYNX(F_,3) ELSE  -
  DYNX(W_,83)*DYNX(F_,3);
DYNX(W_,68) = DYNX(DP_,6)*DYNX(X_,1);
DYNX(W_,74) = IF DYNX(DYNhelp,1) THEN  -DYNX(W_,83)*DYNX(F_,3) ELSE  -
  DYNX(W_,68)*DYNX(F_,3);
 /* Linear system of equations to solve. */
DYNX(F_,2) = RememberSimple_(DYNX(F_,2), 3);
SolveScalarLinearParametric((-0.5026548245743669)*DYNX(DP_,21),"(-0.5026548245743669)*volumeFlow.medium.cv",
   DYNX(W_,74)-DYNX(W_,86),"( -volumeFlow.flowPort_b.H_flow)-volumeFlow.flowPort_a.H_flow",
   DYNX(F_,2),"der(volumeFlow.T)");
 /* End of Equation Block */ 

DYNX(F_,5) =  -DYNX(F_,3);
 /* Linear system of equations to solve. */
DYNX(W_,95) = RememberSimple_(DYNX(W_,95), 4);
SolveScalarLinear( -DYNX(X_,5)," -openTank3.m",  -DYNX(X_,6)," -openTank3.H", 
  DYNX(W_,95),"openTank3.h");
 /* End of Equation Block */ 

if (NewParameters_) {
DYNX(DYNhelp,2) = divinvGuarded(DYNX(DP_,48),"openTank3.medium.cp");
}
DYNX(W_,94) = DYNX(DYNhelp,2)*DYNX(W_,95);
DYNX(W_,54) =  NOT PRE(DYNX(W_,54), 0) AND Greater(DYNX(W_,94),"hysteresis.u", 
  DYNX(DP_,60),"hysteresis.uHigh", 6) OR PRE(DYNX(W_,54), 0) AND GreaterEqual(
  DYNX(W_,94),"hysteresis.u", DYNX(DP_,59),"hysteresis.uLow", 7);
DYNX(W_,53) = IF DYNX(W_,54) THEN DYNX(DP_,30) ELSE DYNX(DP_,36);
DYNX(W_,96) = DYNX(W_,53)*(1+DYNX(DP_,58)*(DYNX(W_,94)-DYNX(DP_,57)));
DYNX(DYNhelp,3) = DYNX(F_,3) >= 0;
DYNX(W_,71) = IF DYNX(DYNhelp,3) THEN DYNX(W_,95)*DYNX(F_,3) ELSE DYNX(W_,68)*
  DYNX(F_,3);
DYNX(F_,6) = DYNX(W_,96)-DYNX(W_,71);
if (NewParameters_) {
DYNX(DYNhelp,4) = divinvGuarded(DYNX(DP_,5),"pipe.medium.rho");
}
DYNX(W_,62) = DYNX(DYNhelp,4)*DYNX(F_,3);
DYNX(DYNhelp,5) = 1.0+DYNX(F_,3) > 1.0;
DYNX(W_,70) = IF DYNX(DYNhelp,5) THEN DYNX(W_,95) ELSE DYNX(W_,68);
if (NewParameters_) {
DYNX(DYNhelp,6) = divinvGuarded(DYNX(DP_,6),"pipe.medium.cp");
}
DYNX(W_,64) = DYNX(DYNhelp,6)*DYNX(W_,70);
DYNX(DYNhelp,7) = 1.0-DYNX(F_,3) > 1.0;
DYNX(W_,73) = IF DYNX(DYNhelp,7) THEN DYNX(W_,83) ELSE DYNX(W_,68);
DYNX(W_,65) = DYNX(DYNhelp,6)*DYNX(W_,73);
DYNX(W_,66) = IF DYNX(W_,62) >= 0 THEN DYNX(X_,1)-DYNX(W_,64) ELSE DYNX(W_,65)-
  DYNX(X_,1);
DYNX(W_,67) = DYNX(X_,1)-(IF DYNX(W_,62) > 0 THEN 1 ELSE IF DYNX(W_,62) < 0
   THEN -1 ELSE 0)*(1-DYNX(DP_,11))*DYNX(W_,66);
DYNX(W_,78) = DYNX(X_,0)-DYNX(W_,67);
DYNX(W_,77) = DYNX(DP_,18)*DYNX(W_,78);
DYNX(W_,75) = IF Greater(DYNX(W_,62),"pipe.volumeFlow", 0.1,"0.1", 8) THEN 10.0*
  DYNX(DP_,12)*DYNX(W_,62)+DYNX(W_,14)*sqr(DYNX(W_,62)-0.1) ELSE IF Less(
  DYNX(W_,62),"pipe.volumeFlow", -0.1,"-0.1", 9) THEN 10.0*DYNX(DP_,12)*
  DYNX(W_,62)-DYNX(W_,14)*sqr(0.1+DYNX(W_,62)) ELSE 10.0*DYNX(DP_,12)*
  DYNX(W_,62);
DYNX(W_,76) = DYNX(DP_,15)*DYNX(W_,62)*DYNX(W_,75);
DYNX(W_,63) = DYNX(W_,77)+DYNX(W_,76);
 /* Linear system of equations to solve. */
DYNX(F_,1) = RememberSimple_(DYNX(F_,1), 5);
SolveScalarLinearParametric((-0.5026548245743669)*DYNX(DP_,7),"(-0.5026548245743669)*pipe.medium.cv",
    -(DYNX(W_,71)+DYNX(W_,74)+DYNX(W_,63))," -(pipe.flowPort_a.H_flow+pipe.flowPort_b.H_flow+pipe.Q_flow)",
   DYNX(F_,1),"der(pipe.T)");
 /* End of Equation Block */ 


 /* Linear system of equations to solve. */
/* Tag: simulation.linear[1] */
DYNX(W_,58) = RememberSimple_(DYNX(W_,58), 6);
SolveScalarLinearParametric(DYNX(DP_,4)-DYNX(DP_,1)*DYNX(DP_,3),"thermalConductor.G-fixedHeatFlow.Q_flow*fixedHeatFlow.alpha",
   DYNX(DP_,4)*DYNX(X_,0)+DYNX(DP_,1)*(1-DYNX(DP_,3)*DYNX(DP_,2)),
  "thermalConductor.G*thermalConductor.port_b.T+fixedHeatFlow.Q_flow*(1-fixedHeatFlow.alpha*fixedHeatFlow.T_ref)",
   DYNX(W_,58),"fixedHeatFlow.port.T");
DYNX(W_,60) = DYNX(W_,58)-DYNX(X_,0);
DYNX(W_,59) =  -DYNX(DP_,1)*(1+DYNX(DP_,3)*(DYNX(W_,58)-DYNX(DP_,2)));
 /* End of Equation Block */ 

DYNX(W_,57) =  -(DYNX(W_,77)+DYNX(W_,59));
 /* Linear system of equations to solve. */
DYNX(F_,0) = RememberSimple_(DYNX(F_,0), 7);
SolveScalarLinearParametric(DYNX(DP_,0),"heatCapacitor.C", DYNX(W_,57),
  "heatCapacitor.port.Q_flow", DYNX(F_,0),"der(heatCapacitor.T)");
 /* End of Equation Block */ 

if (NewParameters_) {
DYNX(DYNhelp,8) = divinvGuarded(DYNX(DP_,38),"openTank1.medium.cp");
}
DYNX(W_,90) = DYNX(DYNhelp,8)*DYNX(W_,91);
DYNX(W_,51) =  NOT PRE(DYNX(W_,51), 3) AND Greater(DYNX(W_,90),"hysteresisT3.u",
   DYNX(DP_,32),"hysteresisT3.uHigh", 10) OR PRE(DYNX(W_,51), 3) AND 
  GreaterEqual(DYNX(W_,90),"hysteresisT3.u", DYNX(DP_,31),"hysteresisT3.uLow", 11);
DYNX(W_,52) = IF DYNX(W_,51) THEN DYNX(DP_,30) ELSE DYNX(DP_,36);
DYNX(W_,88) =  -DYNX(W_,52)*(1+DYNX(DP_,35)*(DYNX(W_,90)-DYNX(DP_,34)));
DYNX(F_,4) =  -(DYNX(W_,86)+DYNX(W_,88));
AssertModelica(LessEqual(DYNX(W_,92),"openTank1.level", DYNX(DP_,44),
  "openTank1.hTank", 12),"openTank1.level <= openTank1.hTank", "Tank got full!");
AssertModelica(LessEqual(DYNX(W_,97),"openTank3.level", DYNX(DP_,54),
  "openTank3.hTank", 13),"openTank3.level <= openTank3.hTank", "Tank got full!");

AcceptedSection1

AcceptedSection2
DYNX(W_,85) = IF DYNX(DYNhelp,7) THEN DYNX(W_,91) ELSE DYNX(W_,83);
DYNX(W_,61) = DYNX(W_,75)+DYNX(DP_,5)*DYNX(DP_,17)*DYNX(DP_,16);
if (NewParameters_) {
DYNX(DYNhelp,9) = divinvGuarded(DYNX(DP_,53),"openTank3.ATank");
}
DYNX(W_,69) = DYNX(DP_,55)+DYNX(DYNhelp,9)*DYNX(X_,5)*DYNX(DP_,56);
DYNX(W_,72) = DYNX(W_,69)-DYNX(W_,61);
if (NewParameters_) {
DYNX(DYNhelp,10) = divinvGuarded(DYNX(DP_,43),"openTank1.ATank");
}
DYNX(W_,84) = DYNX(DP_,45)+DYNX(DYNhelp,10)*DYNX(X_,3)*DYNX(DP_,46);
DYNX(W_,79) = DYNX(W_,84)-DYNX(W_,72);
if (NewParameters_) {
DYNX(DYNhelp,11) = divinvGuarded(DYNX(DP_,20),"volumeFlow.medium.cp");
}
DYNX(W_,80) = DYNX(DYNhelp,11)*DYNX(W_,85);
DYNX(W_,81) = DYNX(DYNhelp,11)*DYNX(W_,73);
DYNX(W_,82) = IF DYNX(W_,48) >= 0 THEN DYNX(X_,2)-DYNX(W_,80) ELSE DYNX(W_,81)-
  DYNX(X_,2);
DYNX(W_,89) = DYNX(DYNhelp,8)*DYNX(W_,85);
DYNX(W_,93) = DYNX(DYNhelp,2)*DYNX(W_,70);

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("heatCapacitor.C", "Heat capacity of element (= cp*m) [J/K]", 0,\
 3000, 0.0,0.0,0.0,0,560)
DeclareState("heatCapacitor.T", "Temperature of element [K|degC]", 0, 358.15, \
0.0,1E+100,300.0,0,560)
DeclareDerivative("heatCapacitor.der(T)", "der(Temperature of element) [K/s]", 0,\
 0, 0.0,0.0,0.0,0,512)
DeclareAlias2("heatCapacitor.der_T", "Time derivative of temperature (= der(T)) [K/s]",\
 "heatCapacitor.der(T)", 1, 6, 0, 0)
DeclareAlias2("heatCapacitor.port.T", "Port temperature [K|degC]", \
"heatCapacitor.T", 1, 1, 0, 4)
DeclareVariable("heatCapacitor.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 57, 0.0, 0.0,0.0,0.0,0,776)
DeclareParameter("fixedHeatFlow.Q_flow", "Fixed heat flow rate at port [W]", 1, \
2414.5, 0.0,0.0,0.0,0,560)
DeclareParameter("fixedHeatFlow.T_ref", "Reference temperature [K|degC]", 2, \
358.15, 0.0,1E+100,300.0,0,560)
DeclareParameter("fixedHeatFlow.alpha", "Temperature coefficient of heat flow rate [1/K]",\
 3, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("fixedHeatFlow.port.T", "Port temperature [K|degC]", 58, 288.15,\
 0.0,1E+100,300.0,0,520)
DeclareVariable("fixedHeatFlow.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 59, 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("thermalConductor.Q_flow", "Heat flow rate from port_a -> port_b [W]",\
 "fixedHeatFlow.port.Q_flow", -1, 5, 59, 0)
DeclareVariable("thermalConductor.dT", "port_a.T - port_b.T [K,]", 60, 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("thermalConductor.port_a.T", "Port temperature [K|degC]", \
"fixedHeatFlow.port.T", 1, 5, 58, 4)
DeclareAlias2("thermalConductor.port_a.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "fixedHeatFlow.port.Q_flow", -1, 5, 59, 132)
DeclareAlias2("thermalConductor.port_b.T", "Port temperature [K|degC]", \
"heatCapacitor.T", 1, 1, 0, 4)
DeclareAlias2("thermalConductor.port_b.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "fixedHeatFlow.port.Q_flow", 1, 5, 59, 132)
DeclareParameter("thermalConductor.G", "Constant thermal conductance of material [W/K]",\
 4, 100, 0.0,0.0,0.0,0,560)
DeclareParameter("pipe.medium.rho", "Density [kg/m3|g/cm3]", 5, 999.7, 0.0,\
1E+100,0.0,0,560)
DeclareParameter("pipe.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 6, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("pipe.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 7, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("pipe.medium.lambda", "Thermal conductivity [W/(m.K)]", 8, \
0.588, 0.0,0.0,0.0,0,560)
DeclareParameter("pipe.medium.nu", "Kinematic viscosity [m2/s]", 9, 1.307E-06, \
0.0,1E+100,0.0,0,560)
DeclareVariable("pipe.m", "Mass of medium [kg]", 0, 0.5026548245743669, 0.0,\
1E+100,0.0,0,513)
DeclareParameter("pipe.T0", "Initial temperature of medium [K|K]", 10, 280.65, \
0.0,1E+100,300.0,0,560)
DeclareVariable("pipe.T0fixed", "Initial temperature guess value or fixed [:#(type=Boolean)]",\
 1, true, 0.0,0.0,0.0,0,515)
DeclareParameter("pipe.tapT", "Defines temperature of heatPort between inlet and outlet temperature",\
 11, 1, 0.0,1.0,0.0,0,560)
DeclareVariable("pipe.dp", "Pressure drop a->b [Pa|bar]", 61, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("pipe.V_flow", "Volume flow a->b [m3/s]", 62, 0, 0.0,0.0,0.0,0,512)
DeclareVariable("pipe.Q_flow", "Heat exchange with ambient [W]", 63, 0.0, \
0.0,0.0,0.0,0,512)
DeclareState("pipe.T", "Outlet temperature of medium [K|degC]", 1, 0.0, 0.0,\
1E+100,300.0,0,544)
DeclareDerivative("pipe.der(T)", "der(Outlet temperature of medium) [K/s]", 1, \
0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("pipe.T_a", "Temperature at flowPort_a [K|degC]", 64, 288.15, \
0.0,1E+100,300.0,0,512)
DeclareVariable("pipe.T_b", "Temperature at flowPort_b [K|degC]", 65, 288.15, \
0.0,1E+100,300.0,0,512)
DeclareVariable("pipe.dT", "Temperature increase of coolant in flow direction [K,]",\
 66, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("pipe.T_q", "Temperature relevant for heat exchange with ambient [K|degC]",\
 67, 288.15, 0.0,1E+100,300.0,0,512)
DeclareVariable("pipe.h", "Medium's specific enthalpy [J/kg]", 68, 0.0, 0.0,0.0,\
0.0,0,2560)
DeclareVariable("pipe.flowPort_a.medium.rho", "Density [kg/m3|g/cm3]", 2, 0.0, \
0.0,1E+100,0.0,0,513)
DeclareVariable("pipe.flowPort_a.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 3, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("pipe.flowPort_a.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 4, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("pipe.flowPort_a.medium.lambda", "Thermal conductivity [W/(m.K)]",\
 5, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("pipe.flowPort_a.medium.nu", "Kinematic viscosity [m2/s]", 6, \
0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("pipe.flowPort_a.p", "[Pa|bar]", 69, 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("pipe.flowPort_a.m_flow", "[kg/s]", "openTank1.der(m)", 1, 6, 3, 132)
DeclareVariable("pipe.flowPort_a.h", "[J/kg]", 70, 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("pipe.flowPort_a.H_flow", "[W]", 71, 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("pipe.flowPort_b.medium.rho", "Density [kg/m3|g/cm3]", 7, 0.0, \
0.0,1E+100,0.0,0,513)
DeclareVariable("pipe.flowPort_b.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 8, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("pipe.flowPort_b.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 9, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("pipe.flowPort_b.medium.lambda", "Thermal conductivity [W/(m.K)]",\
 10, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("pipe.flowPort_b.medium.nu", "Kinematic viscosity [m2/s]", 11, \
0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("pipe.flowPort_b.p", "[Pa|bar]", 72, 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("pipe.flowPort_b.m_flow", "[kg/s]", "openTank1.der(m)", -1, 6, 3, 132)
DeclareVariable("pipe.flowPort_b.h", "[J/kg]", 73, 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("pipe.flowPort_b.H_flow", "[W]", 74, 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("pipe.V_flowLaminar", "Laminar volume flow [m3/s]", 12, 0.1, \
1E-60,1E+100,0.0,0,513)
DeclareParameter("pipe.dpLaminar", "Laminar pressure drop [Pa|bar]", 12, 0, \
0.0,0.0,0.0,0,560)
DeclareParameter("pipe.V_flowNominal", "Nominal volume flow [m3/s]", 13, 1, \
0.0,0.0,0.0,0,560)
DeclareParameter("pipe.dpNominal", "Nominal pressure drop [Pa|bar]", 14, 0, \
0.0,0.0,0.0,0,560)
DeclareParameter("pipe.frictionLoss", "Part of friction losses fed to medium [1]",\
 15, 0, 0.0,1.0,0.0,0,560)
DeclareVariable("pipe.pressureDrop", "[Pa|bar]", 75, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("pipe.volumeFlow", "[m3/s]", "pipe.V_flow", 1, 5, 62, 0)
DeclareVariable("pipe.Q_friction", "[W]", 76, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("pipe.dpNomMin", "[Pa|bar]", 13, 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("pipe.k", "[Pa.s2/m6]", 14, 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("pipe.useHeatPort", "= true, if HeatPort is enabled [:#(type=Boolean)]",\
 15, true, 0.0,0.0,0.0,0,1539)
DeclareParameter("pipe.h_g", "Geodetic height (height difference from flowPort_a to flowPort_b) [m]",\
 16, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("pipe.g", "Gravitation [m/s2]", 17, 9.80665, 0.0,1E+100,0.0,0,560)
DeclareAlias2("pipe.heatPort.T", "Port temperature [K|degC]", "pipe.T_q", 1, 5, 67,\
 4)
DeclareAlias2("pipe.heatPort.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "pipe.Q_flowHeatPort", 1, 5, 77, 132)
DeclareVariable("pipe.Q_flowHeatPort", "Heat flow at conditional heatPort [W]", 77,\
 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("convection.Q_flow", "Heat flow rate from solid -> fluid [W]", \
"pipe.Q_flowHeatPort", 1, 5, 77, 0)
DeclareVariable("convection.dT", "= solid.T - fluid.T [K,]", 78, 0.0, 0.0,0.0,\
0.0,0,512)
DeclareAlias2("convection.Gc", "Signal representing the convective thermal conductance in [W/K] [W/K]",\
 "const.k", 1, 7, 18, 0)
DeclareAlias2("convection.solid.T", "Port temperature [K|degC]", \
"heatCapacitor.T", 1, 1, 0, 4)
DeclareAlias2("convection.solid.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "pipe.Q_flowHeatPort", 1, 5, 77, 132)
DeclareAlias2("convection.fluid.T", "Port temperature [K|degC]", "pipe.T_q", 1, 5,\
 67, 4)
DeclareAlias2("convection.fluid.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "pipe.Q_flowHeatPort", -1, 5, 77, 132)
DeclareParameter("const.k", "Constant output value [W/K]", 18, 300, 0.0,0.0,0.0,\
0,560)
DeclareAlias2("const.y", "Connector of Real output signal [W/K]", "const.k", 1, 7,\
 18, 0)
DeclareParameter("volumeFlow.medium.rho", "Density [kg/m3|g/cm3]", 19, 999.7, \
0.0,1E+100,0.0,0,560)
DeclareParameter("volumeFlow.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 20, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("volumeFlow.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 21, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("volumeFlow.medium.lambda", "Thermal conductivity [W/(m.K)]", 22,\
 0.588, 0.0,0.0,0.0,0,560)
DeclareParameter("volumeFlow.medium.nu", "Kinematic viscosity [m2/s]", 23, \
1.307E-06, 0.0,1E+100,0.0,0,560)
DeclareVariable("volumeFlow.m", "Mass of medium [kg]", 16, 0.5026548245743669, \
0.0,1E+100,0.0,0,513)
DeclareParameter("volumeFlow.T0", "Initial temperature of medium [K|K]", 24, \
280.65, 0.0,1E+100,300.0,0,560)
DeclareVariable("volumeFlow.T0fixed", "Initial temperature guess value or fixed [:#(type=Boolean)]",\
 17, true, 0.0,0.0,0.0,0,515)
DeclareVariable("volumeFlow.tapT", "Defines temperature of heatPort between inlet and outlet temperature",\
 18, 1, 0.0,1.0,0.0,0,513)
DeclareVariable("volumeFlow.dp", "Pressure drop a->b [Pa|bar]", 79, 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("volumeFlow.V_flow", "Volume flow a->b [m3/s]", 48, 0, 0.0,0.0,\
0.0,0,640)
DeclareVariable("volumeFlow.Q_flow", "Heat exchange with ambient [W]", 19, 0, \
0.0,0.0,0.0,0,513)
DeclareState("volumeFlow.T", "Outlet temperature of medium [K|degC]", 2, 0.0, \
0.0,1E+100,300.0,0,544)
DeclareDerivative("volumeFlow.der(T)", "der(Outlet temperature of medium) [K/s]",\
 2, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("volumeFlow.T_a", "Temperature at flowPort_a [K|degC]", 80, \
288.15, 0.0,1E+100,300.0,0,512)
DeclareVariable("volumeFlow.T_b", "Temperature at flowPort_b [K|degC]", 81, \
288.15, 0.0,1E+100,300.0,0,512)
DeclareVariable("volumeFlow.dT", "Temperature increase of coolant in flow direction [K,]",\
 82, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("volumeFlow.T_q", "Temperature relevant for heat exchange with ambient [K|degC]",\
 "volumeFlow.T", 1, 1, 2, 0)
DeclareVariable("volumeFlow.h", "Medium's specific enthalpy [J/kg]", 83, 0.0, \
0.0,0.0,0.0,0,2560)
DeclareVariable("volumeFlow.flowPort_a.medium.rho", "Density [kg/m3|g/cm3]", 20,\
 0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_a.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 21, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_a.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 22, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_a.medium.lambda", "Thermal conductivity [W/(m.K)]",\
 23, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_a.medium.nu", "Kinematic viscosity [m2/s]",\
 24, 0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_a.p", "[Pa|bar]", 84, 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("volumeFlow.flowPort_a.m_flow", "[kg/s]", "openTank1.der(m)", -1, 6,\
 3, 132)
DeclareVariable("volumeFlow.flowPort_a.h", "[J/kg]", 85, 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("volumeFlow.flowPort_a.H_flow", "[W]", 86, 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("volumeFlow.flowPort_b.medium.rho", "Density [kg/m3|g/cm3]", 25,\
 0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_b.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 26, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_b.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 27, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_b.medium.lambda", "Thermal conductivity [W/(m.K)]",\
 28, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_b.medium.nu", "Kinematic viscosity [m2/s]",\
 29, 0.0, 0.0,1E+100,0.0,0,513)
DeclareAlias2("volumeFlow.flowPort_b.p", "[Pa|bar]", "pipe.flowPort_b.p", 1, 5, 72,\
 4)
DeclareAlias2("volumeFlow.flowPort_b.m_flow", "[kg/s]", "openTank1.der(m)", 1, 6,\
 3, 132)
DeclareAlias2("volumeFlow.flowPort_b.h", "[J/kg]", "pipe.flowPort_b.h", 1, 5, 73,\
 4)
DeclareAlias2("volumeFlow.flowPort_b.H_flow", "[W]", "pipe.flowPort_b.H_flow", -1,\
 5, 74, 132)
DeclareVariable("volumeFlow.useVolumeFlowInput", "Enable / disable volume flow input [:#(type=Boolean)]",\
 30, true, 0.0,0.0,0.0,0,515)
DeclareParameter("volumeFlow.constantVolumeFlow", "Volume flow rate [m3/s]", 25,\
 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("volumeFlow.volumeFlow", "[m3/s]", "volumeFlow.V_flow", 1, 5, 48, 0)
DeclareAlias2("volumeFlow.internalVolumeFlow", "[m3/s]", "volumeFlow.V_flow", 1,\
 5, 48, 1024)
DeclareVariable("temperatureSensor.T", "Absolute temperature in degree Celsius as output signal [degC]",\
 87, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("temperatureSensor.port.T", "Port temperature [K|degC]", \
"heatCapacitor.T", 1, 1, 0, 4)
DeclareVariable("temperatureSensor.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 31, 0, 0.0,0.0,0.0,0,777)
DeclareParameter("hysteresisT.uLow", "If y=true and u<uLow, switch to y=false", 26,\
 42, 0.0,0.0,0.0,0,560)
DeclareParameter("hysteresisT.uHigh", "If y=false and u>uHigh, switch to y=true",\
 27, 59, 0.0,0.0,0.0,0,560)
DeclareParameter("hysteresisT.pre_y_start", "Value of pre(y) at initial time [:#(type=Boolean)]",\
 28, false, 0.0,0.0,0.0,0,562)
DeclareAlias2("hysteresisT.u", "[degC]", "temperatureSensor.T", 1, 5, 87, 0)
DeclareVariable("hysteresisT.y", "[:#(type=Boolean)]", 49, false, 0.0,0.0,0.0,0,642)
DeclareAlias2("switch1.u1", "Connector of first Real input signal [W]", \
"const1.k", 1, 7, 29, 0)
DeclareAlias2("switch1.u2", "Connector of Boolean input signal [:#(type=Boolean)]",\
 "hysteresisT.y", 1, 5, 49, 65)
DeclareAlias2("switch1.u3", "Connector of second Real input signal [W]", \
"const8.k", 1, 7, 36, 0)
DeclareVariable("switch1.y", "Connector of Real output signal [W]", 50, 0.0, \
0.0,0.0,0.0,0,640)
DeclareParameter("const1.k", "Constant output value [W]", 29, 2E-05, 0.0,0.0,0.0,\
0,560)
DeclareAlias2("const1.y", "Connector of Real output signal [W]", "const1.k", 1, 7,\
 29, 0)
DeclareParameter("const7.k", "Constant output value [W]", 30, -2800, 0.0,0.0,0.0,\
0,560)
DeclareAlias2("const7.y", "Connector of Real output signal [W]", "const7.k", 1, 7,\
 30, 0)
DeclareParameter("hysteresisT3.uLow", "If y=true and u<uLow, switch to y=false",\
 31, 279.15, 0.0,0.0,0.0,0,560)
DeclareParameter("hysteresisT3.uHigh", "If y=false and u>uHigh, switch to y=true",\
 32, 282.15, 0.0,0.0,0.0,0,560)
DeclareParameter("hysteresisT3.pre_y_start", "Value of pre(y) at initial time [:#(type=Boolean)]",\
 33, true, 0.0,0.0,0.0,0,562)
DeclareAlias2("hysteresisT3.u", "[K]", "openTank1.T", 1, 5, 90, 0)
DeclareVariable("hysteresisT3.y", "[:#(type=Boolean)]", 51, false, 0.0,0.0,0.0,0,642)
DeclareParameter("prescribedHeatFlow2.T_ref", "Reference temperature [K|degC]", 34,\
 293.15, 0.0,1E+100,300.0,0,560)
DeclareParameter("prescribedHeatFlow2.alpha", "Temperature coefficient of heat flow rate [1/K]",\
 35, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("prescribedHeatFlow2.Q_flow", "[W]", 52, 0.0, 0.0,0.0,0.0,0,640)
DeclareAlias2("prescribedHeatFlow2.port.T", "Port temperature [K|degC]", \
"openTank1.T", 1, 5, 90, 4)
DeclareVariable("prescribedHeatFlow2.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 88, 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("switch4.u1", "Connector of first Real input signal [W]", \
"const7.k", 1, 7, 30, 0)
DeclareAlias2("switch4.u2", "Connector of Boolean input signal [:#(type=Boolean)]",\
 "hysteresisT3.y", 1, 5, 51, 65)
DeclareAlias2("switch4.u3", "Connector of second Real input signal [W]", \
"const8.k", 1, 7, 36, 0)
DeclareAlias2("switch4.y", "Connector of Real output signal [W]", \
"prescribedHeatFlow2.Q_flow", 1, 5, 52, 0)
DeclareParameter("const8.k", "Constant output value [W]", 36, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("const8.y", "Connector of Real output signal [W]", "const8.k", 1, 7,\
 36, 0)
DeclareParameter("openTank1.medium.rho", "Density [kg/m3|g/cm3]", 37, 999.7, 0.0,\
1E+100,0.0,0,560)
DeclareParameter("openTank1.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 38, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("openTank1.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 39, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("openTank1.medium.lambda", "Thermal conductivity [W/(m.K)]", 40,\
 0.588, 0.0,0.0,0.0,0,560)
DeclareParameter("openTank1.medium.nu", "Kinematic viscosity [m2/s]", 41, \
1.307E-06, 0.0,1E+100,0.0,0,560)
DeclareParameter("openTank1.T0", "Initial temperature of medium [K|K]", 42, \
280.65, 0.0,1E+100,300.0,0,560)
DeclareVariable("openTank1.T0fixed", "Initial temperature guess value or fixed [:#(type=Boolean)]",\
 32, true, 0.0,0.0,0.0,0,515)
DeclareVariable("openTank1.T_port", "Temperature at flowPort_a [K|degC]", 89, \
288.15, 0.0,1E+100,300.0,0,512)
DeclareVariable("openTank1.T", "Outlet temperature of medium [K|degC]", 90, 0.0,\
 0.0,1E+100,300.0,0,512)
DeclareVariable("openTank1.flowPort.medium.rho", "Density [kg/m3|g/cm3]", 33, \
0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("openTank1.flowPort.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 34, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("openTank1.flowPort.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 35, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("openTank1.flowPort.medium.lambda", "Thermal conductivity [W/(m.K)]",\
 36, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("openTank1.flowPort.medium.nu", "Kinematic viscosity [m2/s]", 37,\
 0.0, 0.0,1E+100,0.0,0,513)
DeclareAlias2("openTank1.flowPort.p", "[Pa|bar]", "volumeFlow.flowPort_a.p", 1, 5,\
 84, 4)
DeclareAlias2("openTank1.flowPort.m_flow", "[kg/s]", "openTank1.der(m)", 1, 6, 3,\
 132)
DeclareAlias2("openTank1.flowPort.h", "[J/kg]", "volumeFlow.flowPort_a.h", 1, 5,\
 85, 4)
DeclareAlias2("openTank1.flowPort.H_flow", "[W]", "volumeFlow.flowPort_a.H_flow", -1,\
 5, 86, 132)
DeclareVariable("openTank1.Exchange", "Exchange of medium via flowport [:#(type=Boolean)]",\
 38, true, 0.0,0.0,0.0,0,1539)
DeclareVariable("openTank1.h", "Specific enthalpy in the volume [J/kg]", 91, 0.0,\
 0.0,0.0,0.0,0,2560)
DeclareParameter("openTank1.ATank", "Cross section of tank [m2]", 43, 0.01, \
0.0,0.0,0.0,0,560)
DeclareParameter("openTank1.hTank", "Height of tank [m]", 44, 0.8, 0.0,0.0,0.0,0,560)
DeclareParameter("openTank1.pAmbient", "Ambient pressure [Pa|bar]", 45, 100000, \
0.0,0.0,0.0,0,560)
DeclareParameter("openTank1.g", "Gravitation [m/s2]", 46, 9.80665, 0.0,1E+100,\
0.0,0,560)
DeclareVariable("openTank1.useHeatPort", "= true, if HeatPort is enabled [:#(type=Boolean)]",\
 39, true, 0.0,0.0,0.0,0,1539)
DeclareState("openTank1.m", "Mass of medium in tank [kg]", 3, 0.0, 0.0,1E+100,\
0.0,0,544)
DeclareDerivative("openTank1.der(m)", "der(Mass of medium in tank) [kg/s]", 3, \
0.0, 0.0,0.0,0.0,0,512)
DeclareState("openTank1.H", "Enthalpy of medium [J]", 4, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("openTank1.der(H)", "der(Enthalpy of medium) [W]", 4, 0.0, \
0.0,0.0,0.0,0,2560)
DeclareAlias2("openTank1.Q_flow", "Heat flow at the optional heatPort [W]", \
"prescribedHeatFlow2.port.Q_flow", -1, 5, 88, 1024)
DeclareAlias2("openTank1.heatPort.T", "Port temperature [K|degC]", "openTank1.T", 1,\
 5, 90, 4)
DeclareAlias2("openTank1.heatPort.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "prescribedHeatFlow2.port.Q_flow", -1, 5, 88, 132)
DeclareVariable("openTank1.level", "Level of medium in tank [m]", 92, 0.8, \
0.0,0.0,0.0,0,528)
DeclareAlias2("openTank1.TTank", "Temperature of medium in tank [K|degC]", \
"openTank1.T", 1, 5, 90, 0)
DeclareParameter("openTank3.medium.rho", "Density [kg/m3|g/cm3]", 47, 999.7, 0.0,\
1E+100,0.0,0,560)
DeclareParameter("openTank3.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 48, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("openTank3.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 49, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("openTank3.medium.lambda", "Thermal conductivity [W/(m.K)]", 50,\
 0.588, 0.0,0.0,0.0,0,560)
DeclareParameter("openTank3.medium.nu", "Kinematic viscosity [m2/s]", 51, \
1.307E-06, 0.0,1E+100,0.0,0,560)
DeclareParameter("openTank3.T0", "Initial temperature of medium [K|K]", 52, \
280.65, 0.0,1E+100,300.0,0,560)
DeclareVariable("openTank3.T0fixed", "Initial temperature guess value or fixed [:#(type=Boolean)]",\
 40, true, 0.0,0.0,0.0,0,515)
DeclareVariable("openTank3.T_port", "Temperature at flowPort_a [K|degC]", 93, \
288.15, 0.0,1E+100,300.0,0,512)
DeclareVariable("openTank3.T", "Outlet temperature of medium [K|degC]", 94, 0.0,\
 0.0,1E+100,300.0,0,512)
DeclareVariable("openTank3.flowPort.medium.rho", "Density [kg/m3|g/cm3]", 41, \
0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("openTank3.flowPort.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 42, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("openTank3.flowPort.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 43, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("openTank3.flowPort.medium.lambda", "Thermal conductivity [W/(m.K)]",\
 44, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("openTank3.flowPort.medium.nu", "Kinematic viscosity [m2/s]", 45,\
 0.0, 0.0,1E+100,0.0,0,513)
DeclareAlias2("openTank3.flowPort.p", "[Pa|bar]", "pipe.flowPort_a.p", 1, 5, 69,\
 4)
DeclareAlias2("openTank3.flowPort.m_flow", "[kg/s]", "openTank1.der(m)", -1, 6, 3,\
 132)
DeclareAlias2("openTank3.flowPort.h", "[J/kg]", "pipe.flowPort_a.h", 1, 5, 70, 4)
DeclareAlias2("openTank3.flowPort.H_flow", "[W]", "pipe.flowPort_a.H_flow", -1, 5,\
 71, 132)
DeclareVariable("openTank3.Exchange", "Exchange of medium via flowport [:#(type=Boolean)]",\
 46, true, 0.0,0.0,0.0,0,1539)
DeclareVariable("openTank3.h", "Specific enthalpy in the volume [J/kg]", 95, 0.0,\
 0.0,0.0,0.0,0,2560)
DeclareParameter("openTank3.ATank", "Cross section of tank [m2]", 53, 0.01, \
0.0,0.0,0.0,0,560)
DeclareParameter("openTank3.hTank", "Height of tank [m]", 54, 0.8, 0.0,0.0,0.0,0,560)
DeclareParameter("openTank3.pAmbient", "Ambient pressure [Pa|bar]", 55, 100000, \
0.0,0.0,0.0,0,560)
DeclareParameter("openTank3.g", "Gravitation [m/s2]", 56, 9.80665, 0.0,1E+100,\
0.0,0,560)
DeclareVariable("openTank3.useHeatPort", "= true, if HeatPort is enabled [:#(type=Boolean)]",\
 47, true, 0.0,0.0,0.0,0,1539)
DeclareState("openTank3.m", "Mass of medium in tank [kg]", 5, 0.0, 0.0,1E+100,\
0.0,0,544)
DeclareDerivative("openTank3.der(m)", "der(Mass of medium in tank) [kg/s]", 5, \
0.0, 0.0,0.0,0.0,0,512)
DeclareState("openTank3.H", "Enthalpy of medium [J]", 6, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("openTank3.der(H)", "der(Enthalpy of medium) [W]", 6, 0.0, \
0.0,0.0,0.0,0,2560)
DeclareVariable("openTank3.Q_flow", "Heat flow at the optional heatPort [W]", 96,\
 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("openTank3.heatPort.T", "Port temperature [K|degC]", "openTank3.T", 1,\
 5, 94, 4)
DeclareAlias2("openTank3.heatPort.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "openTank3.Q_flow", 1, 5, 96, 132)
DeclareVariable("openTank3.level", "Level of medium in tank [m]", 97, 0.0001, \
0.0,0.0,0.0,0,528)
DeclareAlias2("openTank3.TTank", "Temperature of medium in tank [K|degC]", \
"openTank3.T", 1, 5, 94, 0)
DeclareParameter("prescribedHeatFlow3.T_ref", "Reference temperature [K|degC]", 57,\
 293.15, 0.0,1E+100,300.0,0,560)
DeclareParameter("prescribedHeatFlow3.alpha", "Temperature coefficient of heat flow rate [1/K]",\
 58, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("prescribedHeatFlow3.Q_flow", "[W]", 53, 0.0, 0.0,0.0,0.0,0,640)
DeclareAlias2("prescribedHeatFlow3.port.T", "Port temperature [K|degC]", \
"openTank3.T", 1, 5, 94, 4)
DeclareAlias2("prescribedHeatFlow3.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "openTank3.Q_flow", -1, 5, 96, 132)
DeclareAlias2("switch.u1", "Connector of first Real input signal [W]", \
"const7.k", 1, 7, 30, 0)
DeclareAlias2("switch.u2", "Connector of Boolean input signal [:#(type=Boolean)]",\
 "hysteresis.y", 1, 5, 54, 65)
DeclareAlias2("switch.u3", "Connector of second Real input signal [W]", \
"const8.k", 1, 7, 36, 0)
DeclareAlias2("switch.y", "Connector of Real output signal [W]", \
"prescribedHeatFlow3.Q_flow", 1, 5, 53, 0)
DeclareParameter("hysteresis.uLow", "If y=true and u<uLow, switch to y=false", 59,\
 279.15, 0.0,0.0,0.0,0,560)
DeclareParameter("hysteresis.uHigh", "If y=false and u>uHigh, switch to y=true",\
 60, 282.15, 0.0,0.0,0.0,0,560)
DeclareParameter("hysteresis.pre_y_start", "Value of pre(y) at initial time [:#(type=Boolean)]",\
 61, false, 0.0,0.0,0.0,0,562)
DeclareAlias2("hysteresis.u", "[K]", "openTank3.T", 1, 5, 94, 0)
DeclareVariable("hysteresis.y", "[:#(type=Boolean)]", 54, false, 0.0,0.0,0.0,0,642)
DeclareVariable("product1.u1", "Connector of Real input signal 1 [N.kg-2.s4]", 55,\
 0.0, 0.0,0.0,0.0,0,640)
DeclareAlias2("product1.u2", "Connector of Real input signal 2 [W]", "switch1.y", 1,\
 5, 50, 0)
DeclareAlias2("product1.y", "Connector of Real output signal [m3/s]", \
"volumeFlow.V_flow", 1, 5, 48, 0)
DeclareAlias2("feedback.u1", "Commanded input [m]", "openTank1.level", 1, 5, 92,\
 0)
DeclareAlias2("feedback.u2", "Feedback input [m]", "openTank3.level", 1, 5, 97, 0)
DeclareVariable("feedback.y", "[m]", 98, 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("hysteresis1.uLow", "If y=true and u<uLow, switch to y=false", 62,\
 -0.799, 0.0,0.0,0.0,0,560)
DeclareParameter("hysteresis1.uHigh", "If y=false and u>uHigh, switch to y=true",\
 63, 0.799, 0.0,0.0,0.0,0,560)
DeclareParameter("hysteresis1.pre_y_start", "Value of pre(y) at initial time [:#(type=Boolean)]",\
 64, true, 0.0,0.0,0.0,0,562)
DeclareAlias2("hysteresis1.u", "[m]", "feedback.y", 1, 5, 98, 0)
DeclareVariable("hysteresis1.y", "[:#(type=Boolean)]", 56, false, 0.0,0.0,0.0,0,642)
DeclareAlias2("booleanToReal.u", "Connector of Boolean input signal [:#(type=Boolean)]",\
 "hysteresis1.y", 1, 5, 56, 65)
DeclareParameter("booleanToReal.realTrue", "Output signal for true Boolean input [N.kg-2.s4]",\
 65, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("booleanToReal.realFalse", "Output signal for false Boolean input [N.kg-2.s4]",\
 66, -1, 0.0,0.0,0.0,0,560)
DeclareAlias2("booleanToReal.y", "Connector of Real output signal [N.kg-2.s4]", \
"product1.u1", 1, 5, 55, 0)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartPreBlock
preD(DYNX(W_,54),"hysteresis.y", false, 0);
preD(DYNX(W_,56),"hysteresis1.y", false, 1);
preD(DYNX(W_,49),"hysteresisT.y", false, 2);
preD(DYNX(W_,51),"hysteresisT3.y", false, 3);
EndPreBlock
StartEqBlock
DoRemember_(DYNX(F_,0), 0, 7);
DoRemember_(DYNX(F_,1), 0.0, 5);
DoRemember_(DYNX(F_,2), 0.0, 3);
DoRemember_(DYNX(W_,58), 288.15, 6);
DoRemember_(DYNX(W_,91), 0.0, 2);
DoRemember_(DYNX(W_,92), 0.8, 0);
DoRemember_(DYNX(W_,95), 0.0, 4);
DoRemember_(DYNX(W_,97), 0.0001, 1);
EndEqBlock
EndDataBlock
