function out = importSim1(filename, dataLines)
%IMPORTFILE Import data from a text file
%  OUT = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  OUT = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  out = importfile("D:\University\Magistrale\Third_Semester\modeling\MSAS\Assignment_2\src\ex2\out.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Dec-2023 15:58:11

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "stepy", "signalVoltagev", "signalVoltagei", "speedSensorw", "gearboxheatPortQ_flow", "gearboxheatPortT", "gearboxlossyGearw_a", "heatCapacitorportT", "heatCapacitorportQ_flow", "emfw","feedback"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double","double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
out = readtable(filename, opts);

end